# Generated by Django 4.1 on 2022-08-31 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'permissions': (('has_all_access', 'Has all access'),)},
        ),
    ]
