# Generated by Django 4.1 on 2022-09-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_post_options_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='comment'),
            preserve_default=False,
        ),
    ]
