# Generated by Django 4.1 on 2022-09-01 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_comment_author_alter_comment_likes_and_more'),
        ('forum', '0010_alter_comment_options_group_admin'),
    ]

    operations = [
    ]
