# Generated by Django 4.1 on 2022-09-07 11:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_remove_comment_slug_remove_group_member_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelManagers(
            name='comment',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reply',
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
