# Generated by Django 4.1 on 2022-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_dob_alter_userprofile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
