# Generated by Django 4.1 on 2022-09-07 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0013_alter_reply_options_alter_comment_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Event name')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=300, verbose_name='Event Location')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('Cover_image', models.ImageField(default='img/cover_bg.jfif', upload_to='upload/event')),
                ('confirmed_invitees', models.IntegerField(default=0)),
                ('unconfirmed_invitees', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='event_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-start_date_time',),
            },
        ),
    ]
