# Generated by Django 4.1 on 2022-08-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='poll_text',
            field=models.TextField(max_length=300),
        ),
    ]
