# Generated by Django 4.0.5 on 2022-08-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_poll_created_date_alter_poll_poll_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
