# Generated by Django 4.1 on 2022-09-01 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_merge_20220901_1104'),
        ('polls', '0005_alter_poll_options_poll_group_alter_poll_poll_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='forum.group'),
        ),
    ]
